name: Build and Analyze

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      sonarqube:
        image: sonarqube:lts
        ports:
          - 9000:9000
    steps:
      - name: Wait for SonarQube
        run: |
          until curl -s http://localhost:9000/api/system/status | grep '"status":"UP"'; do sleep 5; done