name: Build and Analyze

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      sonarqube:
        image: sonarqube:lts
        ports:
          - 9000:9000
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Wait for SonarQube to Start
        run: |
          echo "Waiting for SonarQube..."
          until curl -s http://localhost:9000/api/system/status | grep '"status":"UP"'; do sleep 5; done

      - name: Run SonarQube Scanner
        run: |
          mvn clean verify sonar:sonar -X -Dsonar.host.url=http://localhost:9000 -Dsonar.login=squ_497832e41264b7d59421df7a601a5ae659f8a929